name: Detekt
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  detekt:
    name: Run Detekt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary-as-pr-comment: always
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/ci' }}
      - run: ./gradlew :objective:detektJvmMain
      - run: ./gradlew :cli:detektMain
      - run: ./gradlew :objective:publishToMavenLocal
